kind: pipeline
name: terraform_drone

steps:
  - name: get_GCP_creds
    image: python:3.8.0
    commands:
      - python3 ./create_json.py
    environment:
      DRONE_GCC_SECRET_DEV:
        from_secret: gcp_creds

  - name: set_up_GCP
    image: jmccann/drone-terraform:latest
    settings:
      actions:
        - validate
        - plan
        - apply
        - destroy
      vars:
        project: "nyt-mbcompdev-dev"
        region: "us-east1"
        zone: "us-east1-b"
        credentials_file: DRONE_GCC_SECRET_DEV.json
    environment:
      DRONE_GCC_SECRET_DEV:
        from_secret: gcp_creds
    when:
      event: push
      branch:
        - master