kind: pipeline
name: terraform_drone

steps:
  - name: set_up_GCP
    image: jmccann/drone-terraform:latest
    actions:
      - validate
      - plan
      - apply
    vars:
      project: "nyt-mbcompdev-dev"
      region: "us-east1"
      zone: "us-east1-b"
    secrets:
      - source: gcp_service_acc_creds
        target: credentials_file
    when:
      event: push
      branch:
        - master