kind: pipeline
name: terraform_drone

steps:
  - name: get_GCP_creds
    image: python:3.8.0
    commands:
      - python3 ./create_json.py
    enviroment:
      DRONE_GCC_SECRET_DEV:
        from_secrets: gcp_service_acc_creds

  - name: set_up_GCP
    image: jmccann/drone-terraform:latest
    commands:
      - echo $CREDS > /tmp/CREDS.json
    settings:
      actions:
        - validate
        - plan
        - apply
      vars:
        project: "nyt-mbcompdev-dev"
        region: "us-east1"
        zone: "us-east1-b"
        credentials_file: /tmp/CREDS.json
#      secrets:
#        - source: $CREDS
#          target: credentials_file
    enviroment:
      DRONE_GCC_SECRET_DEV:
        from_secrets: gcp_service_acc_creds
    when:
      event: push
      branch:
        - master