kind: pipeline
name: terraform_drone

steps:
  - name: set_up_GCP
    image: jmccann/drone-terraform:latest
    actions:
      - validate
      - plan
      - apply
    vars:
      project = "nyt-mbcompdev-dev"
      region = "us-east1"
      zone = "us-east1-b"
      credentials_file = ${gcp_service_acc_creds}
    enviroment:
      credentials_file: ${gcp_service_acc_creds}
    when:
      event: push
      branch:
        - master