kind: pipeline
name: terraform_drone

steps:
  - name: add_creds
    image: jmccann/drone-terraform:latest
    enviroment:
      CREDS:
        from_secrets: gcp_service_acc_creds
      commands:
        - echo $CREDS > /tmp/CREDS.json
    settings:
      actions:
        - validate
        - plan
      vars:
        project: "nyt-mbcompdev-dev"
        region: "us-east1"
        zone: "us-east1-b"
        credentials_file: /tmp/CREDS.json


  - name: set_up_GCP
    image: jmccann/drone-terraform:latest
    settings:
      actions:
        - apply
      vars:
        project: "nyt-mbcompdev-dev"
        region: "us-east1"
        zone: "us-east1-b"
        credentials_file: /tmp/CREDS.json
#      secrets:
#        - source: $CREDS
#          target: credentials_file
    when:
      event: push
      branch:
        - master